apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-chatgpt-deployment
  namespace: chatgpt
  annotations:
    kubernetes.io/change-cause: "Deployed chatgpt version 1.0.1"
spec:
  replicas: {{.Values.numberofReplicas}}
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt-app
        image: {{if .Values.production}} {{.Values.dockerProImage}} {{else}} {{.Values.dockerDevImage}}{{end}}      
        env:
             Node_PORT: {{ .Values.chatgptapp.Node.port }}
             DB_HOST: {{ .Values.chatgptapp.database.host }}
             DB_PORT: {{ .Values.chatgptapp.database.port | default "5432" }}
             DB_USER: {{ .Values.chatgptapp.database.user }}
             DB_PASSWORD: {{ .Values.chatgptapp.database.password }}
             DB_NAME: {{ .Values.chatgptapp.database.name }}
        ports:
          - containerPort: 8080 
        volumeMounts: 
          - name: node-config-volume
            mountPath: /usr/src/app/configs
        resources:
      volumes:
        - name: node-config-volume
          configMap:
           name: node-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-chatgpt-service
  namespace: chatgpt
spec: 
  type: LoadBalancer
  selector:
    app: chatgpt
 ports:
  - name: TCP
    port: 3000
    nodePort: {{.Values.nodePort}}    
