apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-postgres-deployment
  namespace: chatgpt
  annotations:
    kubernetes.io/change-cause: "postgres 1.0.1 Deployment"
spec:
  replicas: {{.Values.numberofReplicas}}    
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{if .Values.production}} {{.Values.dockerProImage}} {{else}} {{.Values.dockerDevImage}}{{end}}
          env:
            data:
              POSTGRES_USER: {{ .Values.postgres.env.POSTGRES_USER }}
              POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
              POSTGRES_DB: {{ .Values.postgres.env.POSTGRES_DB }}  
          ports:
            - containerPort: 5432
          resources:
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-postgres-service
  namespace: chatgpt
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    -  port: 3000
       targetPort: 5432
      

