pipeline {
    agent any
    environment {
        AZURE_CREDENTIALS = credentials('azure-credentials')
    }
    parameters {
        string(name: 'VERSION', defaultValue: '1.0.0', description: 'Version to deploy')
        booleanParam(name: 'EXECUTE_TEST', defaultValue: true, description: '')
        choice(name: 'TYPE', choices: ['New Feature', 'Bug Fixing', 'New Deployment'], description: '')
    }
    stages {
        stage('Checkout') {
            steps {
                echo "Checkout source files from ${BRANCH_NAME}";
            }
        }
        stage('Code Analysis') {
            steps {
                // bat 'Jenkins/Analysis.bat';
                echo "Code analysis successfully completed!";
            }
        }
        stage('Build') {
            steps {
                // bat 'Jenkins/Build.bat'
                echo "Build successfully completed!"
            }
        }
        stage('Test') {
            when {
                expression {
                    EXECUTE_TEST == true
                }
            }
            steps {
                // bat 'Jenkins/Test.bat';
                echo "Unit test successfully completed!"
            }
        }
        stage('Deploy') {
            when {
                expression {
                    BRANCH_NAME == 'main'
                }
            }
            steps {
                // bat 'Jenkins/Deploy.bat';
                echo "Deploying with ${AZURE_CREDENTIALS}"
                echo "Deployed ${VERSION} as part of ${TYPE} successfully!"
            }
        }
    }
    post {
        always {
            echo "This will always run"
        }
        success {
            echo "This will run only if successful"
        }
        failure {
            echo "This will run only if failed"
        }
        unstable {
            echo "This will run only if run was marked as unstable"
        }
        changed {
            echo "This will run only if previous & current state of run was changed"
        }
    }
}
