apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deployment
  namespace: chatgpt
  annotations:
    kubernetes.io/change-cause: "Deployed chatgpt version 1.0.0"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt-app
        image: freelearn2000/chatgpt:1.0.1      
        env:
          - name: NODE_PORT
            value: "8080"
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_PORT
            value: "3000"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "admin123"
          - name: POSTGRES_DB
            value: "chatgpt"
        ports:
          - containerPort: 8080 
        volumeMounts: 
          - name: node-config-volume
            mountPath: /usr/src/app/configs
        resources:
      volumes:
        - name: node-config-volume
          configMap:
           name: node-config

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: chatgpt
spec: 
  type: LoadBalancer
  selector:
    app: chatgpt
  ports:
  - port: 3000
    targetPort: 8080
    nodePort: 30000           
