apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: chatgpt
  annotations:
    kubernetes.io/change-cause: "postgres 1.0.1 Deployment"
spec:
  replicas: 1    
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: freelearn2000/postgresdb:1.0.1
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin123" 
            - name: POSTGRES_DB
              value: "chatgpt"  
          ports:
            - containerPort: 5432
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: chatgpt
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    -  port: 3000
       targetPort: 5432
      

