apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: chatgpt
  annotations:
    kubernetes.io/change-cause: "postgres 1.0.0 Deployment"
spec:
  replicas: 1    
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: freelearn2000/postgresdb:1.0.0
          env:
            #- name: PORT
            #  value: "8080"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_HOST
              value: "localhost"
            - name: POSTGRES_DB
              value: "chatgpt" 
            - name: POSTGRES_PASSWORD
              value: "admin123" 
            - name: POSTGRES_PORT
              value: "5432"   
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
      volumes:
        - name: postgres-storage
          configMap:
            name: node-config-volume
            
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: chatgpt
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    -  port: 3000
       targetPort: 5432
      

