apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}} -chatgpt-deployment
spec:
  replicas: {{.Values.numberofReplicas}}
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt-app
        image: {{if .Values.production}} {{.Values.dockerProImage}} {{else}} {{.Values.dockerDevImage}}{{end}}      
        env:
          - name: NODE_PORT
            value: "8080"
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_PORT
            value: "3000"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "admin123"
          - name: POSTGRES_DB
            value: "chatgpt"
        ports:
          - containerPort: 8080 
        volumeMounts: 
          - name: node-config-volume
            mountPath: /usr/src/app/configs
        resources:
      volumes:
        - name: node-config-volume
          configMap:
           name: node-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-chatgpt-service
spec: 
  type: Nodeport
  selector:
    app: chatgpt
  ports:
  - name: http
    port: 80
    nodePort: {{.Values.nodePort}}           
